name: CI Results

on:
  workflow_call:
    inputs:
      name:
        description: "Added to CI Results job name in parenthesis, e.g. CI Results (Push)"
        type: string
      ci-result:
        description: "Result of the CI job"
        required: true
        type: string

jobs:
  results:
    name: ${{ inputs.name && format('CI Results ({})', inputs.name) || 'CI Results' }}
    runs-on: ubuntu-latest

    steps:
      - run: |
          result="${{ inputs.ci-result }}"
          if [[ $result == "success" ]]; then
            exit 0
          else
            exit 1
          fi
