name: CI Results

on:
  workflow_call:
    inputs:
      name:
        description: "Job name to use instead of CI Results"
        required: false
        type: string
        default: "CI Results"
      ci-result:
        description: "Result of the CI job"
        required: true
        type: string

jobs:
  results:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest

    steps:
      - run: |
          result="${{ inputs.ci-result }}"
          if [[ $result == "success" ]]; then
            exit 0
          else
            exit 1
          fi
