name: Sync Dev

on:
  workflow_call:
    secrets:
      DEPLOY_KEY:
        description: "SSH key for authentication"
        required: true

jobs:
  sync-dev:
    name: Sync main to dev
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout dev
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Merge main into dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git merge origin/main
          git push origin dev
